# backtrack 配置文件示例
# 备份路径列表（支持文件和目录）
backup_paths:
  - /path/to/dir1      # 备份整个目录
  - /path/to/file1.txt # 备份单个文件

# 排除的目录名称（精确匹配）
exclude_dirs:
  - dir_name           # 排除名为 dir_name 的目录

# 排除的文件模式（支持通配符）
exclude_files:
  - "*.log"            # 排除所有.log文件
  - "*.tmp"            # 排除所有.tmp文件

before_script:
  echo 'Starting restore...'  # 还原前执行的命令

after_script:
  echo 'Restore completed.'   # 还原后执行的命令