# https://taskfile.dev

version: "3"

tasks:
  build:
    env:
      OEXPERIMENT: greenteagc
    cmds:
      - task: build_linux_amd64
      - task: build_linux_arm64

  build_linux_amd64:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - echo "Building the project for Linux AMD64..."
      - go build -trimpath -ldflags="-s -w" -o cmd/backtrack_linux_amd64

  build_linux_arm64:
    env:
      GOOS: linux
      GOARCH: arm64
    cmds:
      - echo "Building the project for Linux ARM64..."
      - go build -trimpath -ldflags="-s -w" -o cmd/backtrack_linux_arm64

  build_mac:
    env:
      GOOS: darwin
      GOARCH: arm64
    cmds:
      - echo "Building the project for macOS..."
      - go build -trimpath -ldflags="-s -w" -o cmd/backtrack_macos

  test:
    cmds:
      - echo "Running tests..."
      - go test ./...